// Generated by CoffeeScript 1.8.0
(function() {
  var clickStartGame, randomize, resetUi, sinPrice, stocks;

  stocks = [
    {
      min: 900,
      max: 3500
    }
  ];

  sinPrice = function(min, max, x) {
    return Math.floor((Math.sin(x) + 1.4) * (max + 1 - min) + min);
  };

  randomize = function(min, max, price) {
    return Math.floor(_.random(price - _.random(min, max) / 2, price + _.random(min, max) / 2));
  };

  resetUi = function() {
    $('.turn-nr').text('');
    $('.stock1 .price').text('');
    return $('.profit-container').hide();
  };

  resetUi();

  clickStartGame = Rx.Observable.fromEvent($('.start-new-game'), 'click');

  clickStartGame.subscribe(function() {
    var balance, canBuy, canSell, cannotBuy, cannotSell, clickBuy, clickNextTurn, clickSell, lastTurn, newBuy, newPrice, newSell, newStockAmount, newTurn, profit, progressBar, resettableTimer;
    resetUi();
    $('.end-turn').prop('disabled', false);
    clickNextTurn = Rx.Observable.fromEvent($('.end-turn'), 'click');
    clickBuy = Rx.Observable.fromEvent($('.stock1 .buy'), 'click');
    clickSell = Rx.Observable.fromEvent($('.stock1 .sell'), 'click');
    resettableTimer = clickNextTurn.merge(Rx.Observable.interval(3000).takeUntil(clickNextTurn).merge(clickNextTurn.flatMap(function() {
      return Rx.Observable.interval(3000).takeUntil(clickNextTurn);
    }))).takeUntil(clickStartGame);
    newTurn = resettableTimer.startWith(1).select(function(event, idx) {
      return idx + 1;
    }).take(11);
    lastTurn = newTurn.filter(function(turn) {
      return turn > 10;
    }).combineLatest(clickNextTurn, function(turn, event) {
      return turn;
    }).takeUntil(clickStartGame);
    newPrice = newTurn.map(_.partial(sinPrice, stocks[0].min, stocks[0].max)).map(_.partial(randomize, stocks[0].min, stocks[0].max)).takeUntil(lastTurn).publish();
    newBuy = Rx.Observable.combineLatest(clickBuy, newPrice, function(event, price) {
      return {
        event: event,
        price: price
      };
    }).distinctUntilChanged(function(x) {
      return x.event;
    }).map(function(x) {
      return -x.price;
    }).takeUntil(lastTurn);
    newSell = Rx.Observable.combineLatest(clickSell, newPrice, function(event, price) {
      return {
        event: event,
        price: price
      };
    }).distinctUntilChanged(function(x) {
      return x.event;
    }).map(function(x) {
      return x.price;
    }).takeUntil(lastTurn);
    newStockAmount = newBuy.map(function() {
      return 1;
    }).merge(newSell.map(function() {
      return -1;
    })).scan(0, function(acc, x) {
      return acc + x;
    }).startWith(0).takeUntil(lastTurn);
    balance = Rx.Observable.merge(newBuy, newSell).startWith(10000).scan(function(sum, price) {
      return sum + price;
    }).takeUntil(lastTurn);
    canBuy = Rx.Observable.combineLatest(balance, newPrice, function(balance, price) {
      return {
        balance: balance,
        price: price
      };
    }).filter(function(x) {
      return x.balance >= x.price;
    }).takeUntil(lastTurn);
    cannotBuy = Rx.Observable.combineLatest(balance, newPrice, function(balance, price) {
      return {
        balance: balance,
        price: price
      };
    }).filter(function(x) {
      return x.balance < x.price;
    }).merge(lastTurn).startWith(true);
    canSell = newStockAmount.filter(function(amount) {
      return amount > 0;
    }).takeUntil(lastTurn);
    cannotSell = newStockAmount.filter(function(amount) {
      return amount <= 0;
    }).merge(lastTurn).startWith(true);
    progressBar = newTurn.flatMap(function() {
      return Rx.Observable.timer(0, 1000).take(3);
    }).takeUntil(lastTurn);
    profit = balance.last().map(function(x) {
      return Math.round((x - 10000) / 10000 * 100 * 100) / 100;
    });
    newTurn.subscribe(function(turn) {
      return $('.turn-nr').text(turn);
    });
    newTurn.subscribe(function(turn) {
      return $('.progress').text(3);
    });
    lastTurn.subscribe(function() {
      $('.turn-nr').text('game over');
      return $('.end-turn').prop('disabled', true);
    });
    newPrice.subscribe(function(price) {
      return $('.stock1 .price').text(price);
    });
    balance.subscribe(function(balance) {
      return $('.balance').text(balance);
    });
    canBuy.subscribe(function() {
      return $('.stock1 .buy').prop('disabled', false);
    });
    cannotBuy.subscribe(function() {
      return $('.stock1 .buy').prop('disabled', true);
    });
    canSell.subscribe(function() {
      return $('.stock1 .sell').prop('disabled', false);
    });
    cannotSell.subscribe(function() {
      return $('.stock1 .sell').prop('disabled', true);
    });
    newBuy.subscribe(function() {
      return $('.stock1 .sell').prop('disabled', false);
    });
    newStockAmount.subscribe(function(amount) {
      return $('.stock1 .amount').text(amount);
    });
    progressBar.subscribe(function(t) {
      return $('.progress').text(3 - t);
    });
    profit.subscribe(function(profit) {
      $('.profit-container').show();
      return $('.profit').text(profit + ' %');
    });
    return newPrice.connect();
  });

}).call(this);
